### ISSUE TITLE
No mouse response after connection to the Arduino host shield | Не работает мышка при подключении к плате

### ISSUE THREAD

**Issue by FoxtrotBravoSix** [SunOner/HID_Arduino#9]
I did everything as written in the instructions:

- Installed Arduino IDE
- downloaded repo for logi G and usb host shield in the right directory
- soldered 3 contacts on the board
- uploaded the sketch to the Arduino,

But when I connect the mouse to arduino it doesn't work, I tried with an logi Lightspeed adapter and with a cable directly.
Mouse Logitech Pro X Superlight. 
When im uploaded sketch it shows me in Output this with red color: 
```
Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44
```

What am i doing wrong?

Сделал все как написано в инструкции:

- Установил ArduinoIDE.
- скачал репозиторий для logi G и usb host shield в нужный путь
- припаял 3 контакта на плате
- загрузил скетч в Arduino,

Но когда я подключаю мышь к Arduino, она не работает, я пробовал с адаптером Logi Lightspeed и напрямую с кабелем.
Мышь Logitech Pro X Superlight. 
Когда я загружаю скетч, он показывает ниже в Аутпуте это красным цветом: 
```
Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44
```

Что я делаю не так?

**Comment by igloriousz** [comment]
Use Arduino IDE 1.8x.
